import type { Metadata } from "next";

import { aileron } from '@/lib/fonts'
import { Boldonse as navLogo } from 'next/font/google'
import "./globals.css";


import Navbar from "@/components/Navbar/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLogoFont = navLogo({
  weight: '400',
  variable: '--font-navLogo',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`${aileron.variable} ${navLogoFont.variable} min-h-full flex flex-col`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
