import type { Metadata } from "next";
import { aileron } from '@/lib/fonts'
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`${aileron.variable} min-h-full flex flex-col m-5`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
